---
# tasks file for mysql
- name: Update apt cache
  apt: update_cache=yes cache_valid_time=3600
  become: yes

- name: Install MySql + extension
  apt: name={{ item }} state=present
  become: yes
  with_items:
    - mysql-server
    - python-mysqldb
    - python3-pip
    - python3-mysqldb

- name : Change bind MySql
  become: yes
  lineinfile:
    dest=/etc/mysql/mysql.conf.d/mysqld.cnf
    regexp="(.)+bind-address = 127.0.0.1"
    line="bind-address = 0.0.0.0"
  notify: restart mysql

- name: Create mysql database
  mysql_db: name={{ wp_mysql_db }} state=present
  become: yes

- name: Create mysql mysql_user
  mysql_user:
    name='{{ wp_mysql_user }}'
    password='{{ wp_mysql_password }}'
    priv={{ wp_mysql_db }}.*:ALL
    host='192.168.43.%'
  become: yes

#UFW Configuration
- name: "UFW - Allow MySql on port {{ wp_mysql_port }}"
  ufw:
    rule: allow
    port: "{{ wp_mysql_port }}"
    proto: tcp
  become: yes

- name: UFW - Allow SSH
  ufw:
    rule: allow
    port: "{{ ssh_port }}"
    proto: tcp
  become: yes
