---

- hosts: all
  gather_facts: true

  tasks:
    - name: install python 2
      raw: test -e /usr/bin/python || (apt -y update && apt install -y python-minimal)
      become: yes

    - include_role:
        name: update-upgrade
      when: "ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'"



########################################
#### Proxy serveur configuration ######
########################################
- hosts: proxy

  tasks:
    - include_role:
        name: proxy
      when: "ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'"

    - include_role:
        name: ufw
      when: "ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'"


########################################
#### MySql serveur configuration ######
########################################
- hosts: mysql

  tasks:
    - include_role:
        name: mysql
      when: "ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'"

    - include_role:
        name: proxy-client
      when: "ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'"

    - include_role:
        name: ufw
      when: "ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'"


########################################
#### Apache serveur configuration ######
########################################
- hosts: wp-apache

  environment:
    become: yes
    http_proxy: http://192.168.43.155:3128

  tasks:
    - include_role:
        name: apache
      when: "ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'"

    - include_role:
        name: php
      when: "ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'"

    - include_role:
        name: wordpress
      when: "ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'"

    - include_role:
        name: proxy-client
      when: "ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'"

    - include_role:
        name: ufw
      when: "ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'"


########################################
#### Nginx serveur configuration ######
########################################
- hosts: wp-nginx

  tasks:
    - include_role:
        name: nginx
      when: "ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'"

    - include_role:
        name: php
      when: "ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'"

    - include_role:
        name: wordpress
      when: "ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'"

    - include_role:
        name: proxy-client
      when: "ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'"

    - include_role:
        name: ufw
      when: "ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'"



########################################
#### haproxy serveur configuration #####
########################################
- hosts: haproxy

  tasks:
    - include_role:
        name: haproxy
      when: "ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'"

    - include_role:
        name: proxy-client
      when: "ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'"

    - include_role:
        name: ufw
      when: "ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'"
