---
# tasks file for wordpress
- name: Download WordPress
  get_url:
    url: https://wordpress.org/latest.tar.gz
    dest: /tmp/wordpress.tar.gz
    validate_certs: no

- name: Extract WordPress
  unarchive:
    src: /tmp/wordpress.tar.gz
    dest: /var/www/
    copy: no
  become: yes

- name: Set ownership
  file:
    path: "/var/www/{{ http_host }}"
    state: directory
    recurse: yes
    owner: www-data
    group: www-data
  become: yes

- name: Set permissions for directories
  shell: "/usr/bin/find /var/www/{{ http_host }}/ -type d -exec chmod 750 {} \\;"
  become: yes

- name: Set permissions for files
  shell: "/usr/bin/find /var/www/{{ http_host }}/ -type f -exec chmod 640 {} \\;"
  become: yes

- name: Set up WordPress config file
  template:
    src: "files/wp-config.php.j2"
    dest: "/var/www/wordpress/wp-config.php"
  become: yes
