---
# tasks file for update-upgrade
- name: Set up Sources list
  template:
    src: "files/sources.list.j2"
    dest: "/etc/apt/sources.list"
  become: yes

- name: Update apt repository
  apt: update_cache=yes
  become: yes

- name: Upgrade all packages on servers
  apt: upgrade=dist force_apt_get=yes
  become: yes

- name: Check if a reboot is needed on all servers
  register: reboot_required_file
  stat: path=/var/run/reboot-required get_md5=no
  become: yes

- name: Reboot the box if kernel updated
  become: yes
  command: /sbin/reboot
  when: reboot_required_file.stat.exists
