---
# tasks file for php
- name: Install php extensions
  apt: name={{ item }} state=present
  become: yes
  with_items:
    - php
    - libapache2-mod-php
    - php-mysql
    - php-fpm
#    - php7.2-gd
#    - php7.2-ssh2
#    - php7.2
#    - php7.2-json
#    - php7.2-common
#    - php7.2-fpm
#    - php-common
#    - php-mysql
#    - php-curl
#    - php-gd
#    - php-mbstring
#    - php-xml
#    - php-xmlrpc
#    - php-soap
#    - php-intl
#    - php-zip
